# tests sur plusieurs OS

ubuntu:latest:
  image: "ubuntu:latest"
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential gfortran qt4-qmake libqt4-dev
  script:
    - qmake-qt4
    - make
  only:
    - master
  tags:
    - tag1

fedora:29:
  image: "fedora:29"
  before_script:
    - yum groupinstall -y "Development Tools" && yum install -y gcc-gfortran qt-devel
  script:
    - qmake-qt4
    - make
  only:
    - master
  tags:
    - tag1

