image: "ubuntu:latest"

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential gfortran qt4-qmake

full:
  script:
    - qmake-qt4
    - make
  only:
    - ffts
  tags:
    - tag1

job:
  script:
    - echo "Nothing"

