image: "ubuntu:latest"

before_script:
  - apt update -qq && apt install -y build-essential
  - apt install -y gfortran qt-devel 

compil:
  script:
    - qmake-qt4
    - make
  only:
    - ffts  # uniquement sur la branche ffts pour commencer
  tags:
    - tag1

