image: "ruby:2.6"

before_script:
  - apt update -qq && apt install -y build-essential gfortran qt-devel 

compil:
  script:
    - qmake-qt4
    - make
  only:
    - ffts  # uniquement sur la branche ffts pour commencer
  tags:
    - tag1
  artifacts:
    when: always
    untracked: true
    paths:
      - build
    expire_in: 1d

