# tests sur plusieurs OS

ubuntu:latest:
  image: "ubuntu:latest"
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential gfortran qt4-qmake libqt4-dev
  script:
    - qmake-qt4
    - make
  only:
    - master
  tags:
    - tag1

fedora:29:
  before_script:
    - dnf groupinstall -y "Development Tools" gcc-gfortran qt-devel
  script:
    - qmake-qt4
    - make
  only:
    - master
  tags:
    - tag1

